apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - image: promtail
          name: promtail
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /var/lib/docker/containers
              name: promtail-claim0
              readOnly: true
            - mountPath: /etc/machine-id
              name: promtail-cm1
              readOnly: true
              subPath: machine-id
      restartPolicy: Always
      volumes:
        - name: promtail-claim0
          persistentVolumeClaim:
            claimName: promtail-claim0
            readOnly: true
        - configMap:
            items:
              - key: machine-id
                path: machine-id
            name: promtail-cm1
          name: promtail-cm1