pipeline {
    agent any

    environment {
        PROJECT_NAME = 'clinic-api'
    }

    stages {
    	stage('Inicilização da infraestrutura miníma de testes') {
    		steps {
    			dir('clinic-api') {
    				sh 'docker-compose up -d mysql redis'
    			}
    		}
    	}
    
    	stage('Build da Aplicação Java') {
            steps {
                dir('clinic-api') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        
        stage('Build da imagem Docker') {
            steps {
                dir('clinic-api') {
                    sh "docker build -t $PROJECT_NAME ."
                }
            }
        }

        stage('Derrubar containers antigos') {
            steps {
                dir('clinic-api') {
                    sh 'docker-compose down || true'
                }
            }
        }

        stage('Deploy no Kubernetes') {
    		steps {
        		dir('clinic-api/k8s') {
            		sh 'kubectl apply -f -R .'
        		}
    		}
		}
    }

    post {
        success {
            echo '✅ Deploy realizado com sucesso!'
        }
        failure {
            echo '❌ Erro no deploy.'
        }
    }
}