version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: clinic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - clinic-network

  redis:
    image: redis:7.2
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  clinic-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_api
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    networks:
      - clinic-network
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /var/jenkins_home/workspace/deploy-clinic-api/clinic-api/prometheus:/usr/local/etc/prometheus-config
    ports:
      - "9090:9090"
    command:
      - '--config.file=/usr/local/etc/prometheus-config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - observability

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  promtail:
    build:
      context: ./promtail
      dockerfile: Dockerfile
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - observability
    restart: unless-stopped

volumes:
  mysql-data:
  redis_data:

networks:
  clinic-network:
    driver: bridge
  observability:
    driver: bridge