version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: clinic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - clinic-network

volumes:
  mysql-data:

networks:
  clinic-network:
    driver: bridge