name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start infrastructure with Docker Compose
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: docker-compose up -d mysql redis
        working-directory: ./clinic-api

      - name: Wait for MySQL to be ready
        run: |
          echo "Esperando MySQL iniciar..."
          until docker exec clinic_mysql mysqladmin ping -h "localhost" --silent; do
            sleep 2
          done

      - name: Run tests with Maven
        working-directory: ./clinic-api
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: clinic-api/target/site/jacoco

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: clinic-api/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
