name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Verificar acesso ao Docker
        run: |
          docker version
          docker info

      - name: Set DOCKER_HOST
        run: echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Permitir acesso ao Docker
        run: | 
            sudo chmod 666 /var/run/docker.sock
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            sudo chmod 666 /var/run/docker.sock

      - name: Run tests with Maven
        working-directory: ./clinic-api
        run: mvn clean verify -Dspring.profiles.active=test
