name: Code Quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: code-quality test 
        working-directory: ./../clinic-api
        run: mvn checkstyle:check pmd:check