name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clinic-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (download dependencies)
        run: mvn clean install -DskipTests

      - name: Download and Extract OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip
          mv dependency-check-8.4.0 dependency-check

      - name: Run OWASP Dependency Check
        run: |
          chmod +x dependency-check/bin/dependency-check.sh
          ./dependency-check/bin/dependency-check.sh \
            --project "clinic-api" \
            --scan ./clinic-api \
            --format "HTML" \
            --out ./dependency-check-report

      - name: Upload OWASP report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dependency-check-report
          path: clinic-api/reports