name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (download dependencies)
        run: mvn clean install -DskipTests
        working-directory: clinic-api

      - name: Clean OWASP Dependency Check Data Directory (Important!)
        run: rm -rf ~/.dependency-check 

      - name: Download and Extract OWASP Dependency Check
        run: |
          OWASP_DC_VERSION="9.0.9" # Considere manter a versão mais recente, se não houver problemas com ela
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v${OWASP_DC_VERSION}/dependency-check-${OWASP_DC_VERSION}-release.zip
          unzip dependency-check-${OWASP_DC_VERSION}-release.zip
          
          echo "Conteúdo do diretório atual após unzip:"
          ls -la
          
          echo "Verificando se a pasta 'dependency-check' existe:"
          if [ -d "dependency-check" ]; then
              echo "Diretório 'dependency-check' encontrado com sucesso."
              ls -la dependency-check
          else
              echo "Erro crítico: Diretório 'dependency-check' não encontrado após unzip."
              exit 1
          fi
          
      - name: Run OWASP Dependency Check
        run: |
          chmod +x ./dependency-check/bin/dependency-check.sh
          ./dependency-check/bin/dependency-check.sh \
            --project "clinic-api" \
            --scan ./clinic-api \
            --format "HTML" \
            --out ./owasp-dependency-check-report

      - name: Upload OWASP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: owasp-dependency-check-report/dependency-check-report.html