name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (download dependencies)
        run: mvn clean install -DskipTests
        working-directory: clinic-api

      - name: Download and Extract OWASP Dependency Check
        run: |
          OWASP_DC_VERSION="8.4.0" # Use uma variável para a versão
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v${OWASP_DC_VERSION}/dependency-check-${OWASP_DC_VERSION}-release.zip
          unzip dependency-check-${OWASP_DC_VERSION}-release.zip
          
          echo "Conteúdo do diretório atual após unzip:"
          ls -la
          echo "Procurando diretório descompactado:"
          find . -maxdepth 2 -type d -name "dependency-check-*"
          
          if [ -d "dependency-check-${OWASP_DC_VERSION}" ]; then
              mv dependency-check-${OWASP_DC_VERSION} dependency-check-cli
          elif [ -d "dependency-check-${OWASP_DC_VERSION}-release" ]; then
              mv dependency-check-${OWASP_DC_VERSION}-release dependency-check-cli
          else
              echo "Erro: Não foi possível encontrar o diretório descompactado do Dependency-Check."
              # Opcional: listar o conteúdo para ajudar a depurar
              ls -F
              exit 1 # Falha a etapa se o diretório não for encontrado
          fi
          
          echo "Conteúdo do diretório após renomear:"
          ls -la dependency-check-cli # Verifique se a pasta foi criada e o conteúdo dela
          
      - name: Run OWASP Dependency Check
        run: |
          chmod +x ./dependency-check-cli/bin/dependency-check.sh
          ./dependency-check-cli/bin/dependency-check.sh \
            --project "clinic-api" \
            --scan ./clinic-api \
            --format "HTML" \
            --out ./owasp-dependency-check-report

      - name: Upload OWASP report artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: owasp-dependency-check-report/dependency-check-report.html