name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clinic-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (download dependencies)
        run: mvn clean install -DskipTests

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: clinic-api
          path: ./clinic-api
          format: HTML
          out: reports
          args: >
            --scan ./clinic-api/target
            --enableExperimental

      - name: Upload OWASP report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dependency-check-report
          path: clinic-api/reports