name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (download dependencies)
        run: mvn clean install -DskipTests
        working-directory: clinic-api

      - name: Download and Extract OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip
          # O unzip cria uma pasta como "dependency-check-8.4.0"
          # Vamos renomeá-la para algo mais curto e acessível na raiz do workspace
          mv dependency-check-8.4.0 dependency-check-cli
          ls -la

      - name: Run OWASP Dependency Check
        run: |
          # O Dependency Check CLI agora está em ./dependency-check-cli
          chmod +x ./dependency-check-cli/bin/dependency-check.sh
          ./dependency-check-cli/bin/dependency-check.sh \
            --project "clinic-api" \
            --scan ./clinic-api \
            --format "HTML" \
            --out ./owasp-dependency-check-report # A pasta de saída será criada na raiz do workspace

      - name: Upload OWASP report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: dependency-check-report
          path: owasp-dependency-check-report/dependency-check-report.html